baseURL: https://tarunvelli.site
languageCode: en-us
title: Tarun Vellishetty
theme: mini
publishDir: "docs"

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish) / da (Danish), default 'en'
defaultContentLanguage: en

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: https://github.com/tarunvelli
  linkedin: https://www.linkedin.com/in/tarun-velli
  email: mailto:tarunvelli@gmail.com

# Site parameters
params:
  # Site Author
  author: Tarun Vellishetty
  # Author biography
  bio: Hey look I have a blog
  # Site Description, used in HTML meat
  description: Hey look I have a blog

  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: false
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: false
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: false
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: false
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: ''

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js